[theme]
# Primary colors
primaryColor = "#00d4ff"
backgroundColor = "#0a0e1a"
secondaryBackgroundColor = "#1a1f2e"
textColor = "#ffffff"

# Font configuration
font = "sans serif"

# Additional theme settings
base = "dark"

[server]
# Server configuration
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

# File upload settings
maxUploadSize = 10
maxMessageSize = 10

[browser]
# Browser settings
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[runner]
# Runner settings
magicEnabled = true
installTracer = false
fixMatplotlib = true

[logger]
# Logging configuration
level = "info"
messageFormat = "%(asctime)s.%(msecs)03d %(name)s: %(levelname)s: %(message)s"

[client]
# Client settings
caching = true
displayEnabled = true
showErrorDetails = true

[global]
# Global settings
developmentMode = false
logLevel = "info"
unitTest = false

# Custom CSS and theming
[ui]
hideTopBar = false
hideSidebarNav = false

# Additional configuration to disable slider labels
[deprecation]
showPyplotGlobalUse = false
showfileUploaderEncoding = false

# Widget configuration
[widget]
# Disable slider endpoint labels
sliderEndpointLabels = false
